"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter
at a random position.

Return the letter that was added to t.


Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.


Example 2:
Input: s = "", t = "y"
Output: "y"


Constraints:
    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.

"""

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:

        cmap = {}
        for c in s:
            if c not in cmap:
                cmap[c] = 1
            else:
                cmap[c] += 1

        for c in t:
            if c not in cmap:
                return c
            else:
                cmap[c] -= 1

        for k, v in cmap.items():
            if v != 0:
                return k

        return ""